"""
Fetch candidate hospitals in the study area from OpenStreetMap.

CLAUDE.md section 6.2. Writes:
  * data/hospitals.raw.json   -- every raw result, untouched
  * docs/HOSPITAL_REVIEW.md   -- a checklist for a HUMAN to verify

    .venv/Scripts/python.exe scripts/fetch-hospitals.py

This script does NOT decide which results are real hospitals. Some will be
clinics, dispensaries or closed facilities. A human reviews the checklist and
records verified facts in data/hospital-overrides.json; only then does
build-hospitals.ts produce the curated file.

Nothing here invents a fact. Capacity and capability are NEVER guessed in this
script -- if OSM does not say it, the field is absent and gets labelled
simulated downstream.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

import osmnx as ox

# Windows consoles default to cp1252, which cannot print non-Latin hospital
# names. The files themselves are always written as UTF-8.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
AREA_TS = ROOT / "src" / "config" / "area.ts"
OUT_RAW = ROOT / "data" / "hospitals.raw.json"
OUT_REVIEW = ROOT / "docs" / "HOSPITAL_REVIEW.md"

# Tags OSM may carry that we care about. Recorded verbatim when present.
TAGS_OF_INTEREST = [
    "emergency",
    "beds",
    "capacity:beds",
    "operator",
    "operator:type",
    "healthcare",
    "healthcare:speciality",
    "amenity",
    "phone",
    "website",
    "addr:street",
    "addr:suburb",
    "opening_hours",
]


def read_area() -> dict[str, float]:
    text = AREA_TS.read_text(encoding="utf-8")
    area: dict[str, float] = {}
    for key in ("minLat", "maxLat", "minLon", "maxLon"):
        match = re.search(rf"\b{key}\s*:\s*(-?\d+(?:\.\d+)?)", text)
        if not match:
            sys.exit(f"Could not find {key} in {AREA_TS}.")
        area[key] = float(match.group(1))
    return area


def fetch(bbox: tuple[float, float, float, float]) -> list[dict[str, Any]]:
    """Query Overpass via OSMnx. Multiple tag keys are OR-ed."""
    features = ox.features.features_from_bbox(
        bbox, tags={"amenity": "hospital", "healthcare": "hospital"}
    )
    if features.empty:
        return []

    # Project to a metric CRS before taking centroids, so the centroid of an
    # area is geometrically sound rather than computed in degrees.
    metric = features.to_crs(features.estimate_utm_crs())
    centroids = metric.geometry.centroid.to_crs("EPSG:4326")
    # Footprint area in square metres. This is a DATA-DERIVED size proxy: a
    # mapped hospital campus is larger than a one-room clinic. Nodes have no
    # polygon and so get 0. Used for tiering instead of anyone's memory of
    # which hospitals are big.
    areas = metric.geometry.area

    results: list[dict[str, Any]] = []
    for (element_type, osm_id), row in features.iterrows():
        point = centroids.loc[(element_type, osm_id)]
        tags = {
            key: row[key]
            for key in TAGS_OF_INTEREST
            if key in row.index and row[key] is not None and str(row[key]) != "nan"
        }
        results.append(
            {
                "osmType": element_type,
                "osmId": int(osm_id),
                "name": (
                    str(row["name"])
                    if "name" in row.index and str(row.get("name")) != "nan"
                    else None
                ),
                "lat": round(float(point.y), 5),
                "lng": round(float(point.x), 5),
                "geometryType": row.geometry.geom_type,
                "footprintM2": round(float(areas.loc[(element_type, osm_id)]), 1),
                "tags": {k: str(v) for k, v in tags.items()},
            }
        )

    results.sort(key=lambda r: (r["name"] or "zzz").lower())
    return results


def write_review(results: list[dict[str, Any]], area: dict[str, float]) -> None:
    """Generate the human checklist."""
    original_south = 18.961517
    in_original = [r for r in results if r["lat"] >= original_south]

    lines: list[str] = []
    lines.append("# Hospital review checklist")
    lines.append("")
    lines.append(
        "**A human must complete this before `build-hospitals.ts` runs.** "
        "Generated by `scripts/fetch-hospitals.py` from OpenStreetMap."
    )
    lines.append("")
    lines.append(
        "These are raw OSM results for `amenity=hospital` or "
        "`healthcare=hospital` inside the study area. Some will be clinics, "
        "dispensaries, or closed facilities. OpenStreetMap does **not** record "
        "trauma capability or live bed counts, so those never come from here."
    )
    lines.append("")
    lines.append("## Counts")
    lines.append("")
    lines.append(f"- Extended box (in use, south edge {area['minLat']}): **{len(results)}** results")
    lines.append(
        f"- Original northern box (south edge {original_south}): **{len(in_original)}** results"
    )
    lines.append("")
    lines.append(
        "The extended box is used regardless (locked decision 1); the "
        "comparison is for the README."
    )
    lines.append("")
    lines.append("## How to review")
    lines.append("")
    lines.append("For each row, check it against BMC or the hospital's own site, then:")
    lines.append("")
    lines.append("1. Decide **include**: is this a real, currently operating hospital?")
    lines.append("2. If you can verify them, record `traumaCapable`, `icu` and `beds`.")
    lines.append("3. Put the result in `data/hospital-overrides.json`, keyed by OSM id.")
    lines.append("4. Anything you cannot verify stays absent and is labelled *simulated*.")
    lines.append("")
    lines.append(
        "If fewer than 3 hospitals qualify as trauma-capable, **stop and ask**, "
        "rather than guessing names (section 6.2)."
    )
    lines.append("")
    lines.append("## Results")
    lines.append("")
    lines.append(
        "| # | Name | OSM | Lat, Lng | `emergency` | `beds` | `operator` | Speciality | Include? | Verified facts |"
    )
    lines.append("| - | ---- | --- | -------- | ----------- | ------ | ---------- | ---------- | -------- | -------------- |")

    for i, r in enumerate(results, start=1):
        tags = r["tags"]
        name = r["name"] or "_(unnamed)_"
        osm_url = f"[{r['osmType']}/{r['osmId']}](https://www.openstreetmap.org/{r['osmType']}/{r['osmId']})"
        beds = tags.get("beds") or tags.get("capacity:beds") or ""
        speciality = tags.get("healthcare:speciality", "")
        lines.append(
            f"| {i} | {name} | {osm_url} | {r['lat']}, {r['lng']} "
            f"| {tags.get('emergency', '')} | {beds} | {tags.get('operator', '')} "
            f"| {speciality} | ☐ | |"
        )

    lines.append("")
    lines.append("## Tag coverage")
    lines.append("")
    with_emergency = sum(1 for r in results if r["tags"].get("emergency"))
    with_beds = sum(
        1 for r in results if r["tags"].get("beds") or r["tags"].get("capacity:beds")
    )
    with_operator = sum(1 for r in results if r["tags"].get("operator"))
    unnamed = sum(1 for r in results if not r["name"])
    lines.append(f"- Tagged `emergency`: {with_emergency} of {len(results)}")
    lines.append(f"- Tagged `beds`: {with_beds} of {len(results)}")
    lines.append(f"- Tagged `operator`: {with_operator} of {len(results)}")
    lines.append(f"- Unnamed: {unnamed} of {len(results)}")
    lines.append("")
    lines.append(
        "Low `beds` coverage is expected and is exactly why bed counts are "
        "simulated and labelled as such."
    )
    lines.append("")

    OUT_REVIEW.parent.mkdir(parents=True, exist_ok=True)
    OUT_REVIEW.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    area = read_area()
    bbox = (area["minLon"], area["minLat"], area["maxLon"], area["maxLat"])

    print(f"osmnx {ox.__version__}")
    print(f"bbox (left, bottom, right, top) = {bbox}")
    ox.settings.use_cache = True

    print("querying Overpass for amenity=hospital / healthcare=hospital...")
    results = fetch(bbox)
    print(f"  {len(results)} result(s)")

    OUT_RAW.parent.mkdir(parents=True, exist_ok=True)
    OUT_RAW.write_text(json.dumps(results, indent=2, ensure_ascii=False), encoding="utf-8")
    write_review(results, area)

    print(f"\nwrote {OUT_RAW.relative_to(ROOT)}")
    print(f"wrote {OUT_REVIEW.relative_to(ROOT)}")
    print("\nSTOP: a human reviews docs/HOSPITAL_REVIEW.md before build-hospitals.ts.")

    for r in results:
        tags = r["tags"]
        flag = " [emergency]" if tags.get("emergency") == "yes" else ""
        print(f"  - {r['name'] or '(unnamed)'}{flag}")


if __name__ == "__main__":
    main()
